### ISSUE TITLE
Program cannot detect Garry's Mod install on any drive not the C:\ drive

### ISSUE THREAD

**Issue by Aqua-Vision** [storm37000/garrysmod-fixr-uppr#1]
I know this program is old, but it is a very useful tool to a lot of people.

Say I have my Garry's Mod install on D:\SteamLibrary\steamapps\common\Garrys Mod, and the program cannot detect Garry's Mod on that drive. Any workarounds or any way to fix this?

**Comment by storm37000** [comment]
It should be able to detect gmod on any drive as long as its inside a steam library that is actively registered with steam and you are using at least version 0.5.

**Comment by Aqua-Vision** [comment]
The thing is, I have it installed on D:\SteamLibrary and yet I have this
![error](https://user-images.githubusercontent.com/68039369/149638877-459b5642-fd81-4d3c-85df-1d0de2e4489f.png)
:

**Comment by storm37000** [comment]
It did work for me when I tested, It reads a steam config file that stores all the libraries, hopefully steam didnt change how it works.

**Comment by Aqua-Vision** [comment]
I registered the directory in steam, I think they changed how it works (panic noises)

**Comment by Aqua-Vision** [comment]
> It did work for me when I tested, It reads a steam config file that stores all the libraries, hopefully steam didnt change how it works.

i still need help with this, I am in major pain trying to figure this out
